### ISSUE TITLE
questions about feature_map_analysis

### ISSUE THREAD

**Issue by vogdb** [derekreiman/PopPhy-CNN#5]
- Should it be https://github.com/derekreiman/PopPhy-CNN/blob/master/src/feature_map_analysis.py#L72?
  ```
  num_maps = w.shape[0]`
  ```
  instead of
  ```
  num_maps = w.shape[1]`
  ```
  as the first is `64` and the latter is `1`

- Should it be https://github.com/derekreiman/PopPhy-CNN/blob/master/src/feature_map_analysis.py#L128?
  ```
  w = np.rot90(np.rot90(net.layers[0].w.container.data[j][0]))
  ```
  instead of
  ```
  w = np.rot90(np.rot90(net.layers[0].w.container.data[0][0]))
  ```
  as the first iterates over `64` kernels and the latter always uses the first kernel.

**Comment by vogdb** [comment]
@derekreiman or @aametwally can you please look?

**Comment by derekreiman** [comment]
Sorry for the delay and thank you for finding these. Yes you are correct and I have fixed the bugs in the code.
